import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'es' | 'fr' | 'de' | 'it' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  translations: Record<string, string>;
}

const translations = {
  en: {
    welcome: "MATRIX ORACLE",
    subtitle: "Enter a realm where artificial intelligence and human consciousness converge on the Sui blockchain.",
    initConnection: "Initialize Connection",
    neuralProcessing: "Neural Processing",
    neuralDesc: "Advanced AI algorithms powered by quantum computing",
    suiIntegration: "Sui Integration",
    suiDesc: "Seamless blockchain operations on Sui's high-performance network",
    secureProtocol: "Secure Protocol",
    secureDesc: "Military-grade encryption for all operations",
    performance: "High Performance",
    performanceDesc: "Leveraging Sui's parallel execution engine",
    smartContracts: "Smart Contracts",
    smartContractsDesc: "Advanced Move-based smart contracts",
    connectWallet: "Connect SUI Wallet",
    totalStake: "Total Stake",
    epoch: "Epoch",
    marketCap: "Market Cap",
    tps: "TPS (Peak)",
    validators: "Validators",
    selectLanguage: "Select Language",
    chooseLanguage: "Choose your preferred language",
    decryptingData: "Decrypting agent data...",
    agents: "Agents",
    console: "Console",
    systems: "Systems",
    network: "Network",
    platformStatus: "Platform Status",
    systemStatus: "System Status",
    online: "Online",
    projectOverview: "PROJECT OVERVIEW",
    error: "Error",
    errorFetchingData: "Error fetching data. Please try again later.",
    matrixAiAgent: "MATRIX AI AGENT",
    home: "Home",
    agentDescription: "Interface with our advanced AI agent, trained on the principles of the Matrix. Unlock the secrets of the digital realm through natural conversation.",
    capabilities: "Capabilities",
    nlpCapability: "Natural Language Processing",
    marketAnalysis: "Market Analysis & Token Launch",
    problemSolving: "Advanced Problem Solving",
    accessAgent: "Access AI Agent",
    aiAgentInterface: "Matrix AI Agent Interface",
    aiLaunchedTokens: "AI LAUNCHED TOKENS",
    launchDate: "Launch Date",
    matrixAiDesc: "AI-powered DeFi protocol launched after analyzing market conditions",
    neuralNetDesc: "Decentralized machine learning network token",
    cyberCoreDesc: "AI governance token for decentralized systems"
  },
  es: {
    welcome: "ORÁCULO MATRIX",
    subtitle: "Entra en un reino donde la inteligencia artificial y la consciencia humana convergen en la blockchain Sui.",
    initConnection: "Iniciar Conexión",
    neuralProcessing: "Procesamiento Neural",
    neuralDesc: "Algoritmos avanzados de IA",
    suiIntegration: "Integración Sui",
    suiDesc: "Operaciones blockchain fluidas",
    secureProtocol: "Protocolo Seguro",
    secureDesc: "Encriptación de grado militar",
    performance: "Alto Rendimiento",
    performanceDesc: "Motor de ejecución paralela de Sui",
    smartContracts: "Contratos Inteligentes",
    smartContractsDesc: "Contratos inteligentes Move",
    connectWallet: "Conectar Billetera SUI",
    totalStake: "Stake Total",
    epoch: "Época",
    marketCap: "Cap. de Mercado",
    tps: "TPS (Pico)",
    validators: "Validadores",
    selectLanguage: "Seleccionar Idioma",
    chooseLanguage: "Elige tu idioma preferido",
    decryptingData: "Descifrando datos del agente...",
    agents: "Agentes",
    console: "Consola",
    systems: "Sistemas",
    network: "Red",
    platformStatus: "Estado de la Plataforma",
    systemStatus: "Estado del Sistema",
    online: "En línea",
    projectOverview: "DESCRIPCIÓN DEL PROYECTO",
    error: "Error",
    errorFetchingData: "Error al obtener datos. Por favor, inténtelo más tarde.",
    matrixAiAgent: "AGENTE DE IA MATRIX",
    home: "Inicio",
    agentDescription: "Interactúa con nuestro agente de IA avanzado, entrenado en los principios de Matrix. Desbloquea los secretos del reino digital a través de la conversación natural.",
    capabilities: "Capacidades",
    nlpCapability: "Procesamiento de Lenguaje Natural",
    marketAnalysis: "Análisis de Mercado y Lanzamiento de Tokens",
    problemSolving: "Resolución Avanzada de Problemas",
    accessAgent: "Acceder al Agente de IA",
    aiAgentInterface: "Interfaz del Agente de IA Matrix",
    aiLaunchedTokens: "TOKENS LANZADOS POR IA",
    launchDate: "Fecha de Lanzamiento",
    matrixAiDesc: "Protocolo DeFi impulsado por IA lanzado después de analizar las condiciones del mercado",
    neuralNetDesc: "Token de red de aprendizaje automático descentralizado",
    cyberCoreDesc: "Token de gobernanza de IA para sistemas descentralizados"
  },
  fr: {
    welcome: "ORACLE MATRIX",
    subtitle: "Entrez dans un monde où l'intelligence artificielle et la conscience humaine convergent sur la blockchain Sui.",
    initConnection: "Initialiser la Connexion",
    neuralProcessing: "Traitement Neural",
    neuralDesc: "Algorithmes IA avancés",
    suiIntegration: "Intégration Sui",
    suiDesc: "Opérations blockchain fluides",
    secureProtocol: "Protocole Sécurisé",
    secureDesc: "Cryptage militaire",
    performance: "Haute Performance",
    performanceDesc: "Moteur d'exécution parallèle Sui",
    smartContracts: "Contrats Intelligents",
    smartContractsDesc: "Contrats intelligents Move",
    connectWallet: "Connecter Portefeuille SUI",
    totalStake: "Stake Total",
    epoch: "Époque",
    marketCap: "Cap. Marché",
    tps: "TPS (Pic)",
    validators: "Validateurs",
    selectLanguage: "Choisir la Langue",
    chooseLanguage: "Choisissez votre langue préférée",
    decryptingData: "Décryptage des données de l'agent...",
    agents: "Agents",
    console: "Console",
    systems: "Systèmes",
    network: "Réseau",
    platformStatus: "État de la Plateforme",
    systemStatus: "État du Système",
    online: "En ligne",
    projectOverview: "APERÇU DU PROJET",
    error: "Erreur",
    errorFetchingData: "Erreur lors de la récupération des données. Veuillez réessayer plus tard.",
    matrixAiAgent: "AGENT IA MATRIX",
    home: "Accueil",
    agentDescription: "Interagissez avec notre agent IA avancé, formé aux principes de Matrix. Débloquez les secrets du domaine numérique grâce à la conversation naturelle.",
    capabilities: "Capacités",
    nlpCapability: "Traitement du Langage Naturel",
    marketAnalysis: "Analyse de Marché et Lancement de Tokens",
    problemSolving: "Résolution Avancée de Problèmes",
    accessAgent: "Accéder à l'Agent IA",
    aiAgentInterface: "Interface de l'Agent IA Matrix",
    aiLaunchedTokens: "TOKENS LANCÉS PAR L'IA",
    launchDate: "Date de Lancement",
    matrixAiDesc: "Protocole DeFi alimenté par l'IA lancé après analyse des conditions du marché",
    neuralNetDesc: "Token de réseau d'apprentissage automatique décentralisé",
    cyberCoreDesc: "Token de gouvernance IA pour systèmes décentralisés"
  },
  de: {
    welcome: "MATRIX ORAKEL",
    subtitle: "Betreten Sie eine Welt, in der künstliche Intelligenz und menschliches Bewusstsein auf der Sui-Blockchain zusammenkommen.",
    initConnection: "Verbindung Initialisieren",
    neuralProcessing: "Neurale Verarbeitung",
    neuralDesc: "Fortgeschrittene KI-Algorithmen",
    suiIntegration: "Sui Integration",
    suiDesc: "Nahtlose Blockchain-Operationen",
    secureProtocol: "Sicheres Protokoll",
    secureDesc: "Militärische Verschlüsselung",
    performance: "Hohe Leistung",
    performanceDesc: "Sui Parallel-Ausführungsengine",
    smartContracts: "Smart Contracts",
    smartContractsDesc: "Move Smart Contracts",
    connectWallet: "SUI Wallet Verbinden",
    totalStake: "Gesamt-Stake",
    epoch: "Epoche",
    marketCap: "Marktkapitalisierung",
    tps: "TPS (Spitze)",
    validators: "Validatoren",
    selectLanguage: "Sprache Wählen",
    chooseLanguage: "Wählen Sie Ihre bevorzugte Sprache",
    decryptingData: "Entschlüssele Agentendaten...",
    agents: "Agenten",
    console: "Konsole",
    systems: "Systeme",
    network: "Netzwerk",
    platformStatus: "Plattformstatus",
    systemStatus: "Systemstatus",
    online: "Online",
    projectOverview: "PROJEKTÜBERSICHT",
    error: "Fehler",
    errorFetchingData: "Fehler beim Abrufen der Daten. Bitte versuchen Sie es später erneut.",
    matrixAiAgent: "MATRIX KI-AGENT",
    home: "Start",
    agentDescription: "Interagieren Sie mit unserem fortschrittlichen KI-Agenten, der in den Prinzipien der Matrix geschult wurde. Erschließen Sie die Geheimnisse der digitalen Welt durch natürliche Konversation.",
    capabilities: "Fähigkeiten",
    nlpCapability: "Natürliche Sprachverarbeitung",
    marketAnalysis: "Marktanalyse & Token-Launch",
    problemSolving: "Fortgeschrittene Problemlösung",
    accessAgent: "KI-Agent Zugriff",
    aiAgentInterface: "Matrix KI-Agent Schnittstelle",
    aiLaunchedTokens: "KI-GESTARTETE TOKENS",
    launchDate: "Startdatum",
    matrixAiDesc: "KI-gesteuertes DeFi-Protokoll, gestartet nach Analyse der Marktbedingungen",
    neuralNetDesc: "Dezentrales Machine Learning Netzwerk Token",
    cyberCoreDesc: "KI-Governance-Token für dezentrale Systeme"
  },
  it: {
    welcome: "ORACOLO MATRIX",
    subtitle: "Entra in un regno dove l'intelligenza artificiale e la coscienza umana convergono sulla blockchain Sui.",
    initConnection: "Inizializza Connessione",
    neuralProcessing: "Elaborazione Neurale",
    neuralDesc: "Algoritmi IA avanzati",
    suiIntegration: "Integrazione Sui",
    suiDesc: "Operazioni blockchain fluide",
    secureProtocol: "Protocollo Sicuro",
    secureDesc: "Crittografia militare",
    performance: "Alta Performance",
    performanceDesc: "Motore di esecuzione parallela Sui",
    smartContracts: "Smart Contract",
    smartContractsDesc: "Smart contract Move",
    connectWallet: "Connetti Wallet SUI",
    totalStake: "Stake Totale",
    epoch: "Epoca",
    marketCap: "Cap. di Mercato",
    tps: "TPS (Picco)",
    validators: "Validatori",
    selectLanguage: "Seleziona Lingua",
    chooseLanguage: "Scegli la tua lingua preferita",
    decryptingData: "Decrittazione dati agente...",
    agents: "Agenti",
    console: "Console",
    systems: "Sistemi",
    network: "Rete",
    platformStatus: "Stato Piattaforma",
    systemStatus: "Stato Sistema",
    online: "Online",
    projectOverview: "PANORAMICA PROGETTO",
    error: "Errore",
    errorFetchingData: "Errore nel recupero dei dati. Si prega di riprovare più tardi.",
    matrixAiAgent: "AGENTE IA MATRIX",
    home: "Home",
    agentDescription: "Interagisci con il nostro agente IA avanzato, addestrato sui principi di Matrix. Sblocca i segreti del regno digitale attraverso la conversazione naturale.",
    capabilities: "Capacità",
    nlpCapability: "Elaborazione del Linguaggio Naturale",
    marketAnalysis: "Analisi di Mercato e Lancio Token",
    problemSolving: "Risoluzione Avanzata dei Problemi",
    accessAgent: "Accedi all'Agente IA",
    aiAgentInterface: "Interfaccia Agente IA Matrix",
    aiLaunchedTokens: "TOKEN LANCIATI DALL'IA",
    launchDate: "Data di Lancio",
    matrixAiDesc: "Protocollo DeFi basato su IA lanciato dopo l'analisi delle condizioni di mercato",
    neuralNetDesc: "Token di rete di apprendimento automatico decentralizzato",
    cyberCoreDesc: "Token di governance IA per sistemi decentralizzati"
  },
  zh: {
    welcome: "矩阵神谕",
    subtitle: "进入一个人工智能与人类意识在Sui区块链上融合的领域。",
    initConnection: "初始化连接",
    neuralProcessing: "神经处理",
    neuralDesc: "先进AI算法",
    suiIntegration: "Sui集成",
    suiDesc: "无缝区块链操作",
    secureProtocol: "安全协议",
    secureDesc: "军事级加密",
    performance: "高性能",
    performanceDesc: "Sui并行执行引擎",
    smartContracts: "智能合约",
    smartContractsDesc: "Move智能合约",
    connectWallet: "连接SUI钱包",
    totalStake: "总质押量",
    epoch: "周期",
    marketCap: "市值",
    tps: "TPS (峰值)",
    validators: "验证者",
    selectLanguage: "选择语言",
    chooseLanguage: "选择您的首选语言",
    decryptingData: "正在解密代理数据...",
    agents: "代理",
    console: "控制台",
    systems: "系统",
    network: "网络",
    platformStatus: "平台状态",
    systemStatus: "系统状态",
    online: "在线",
    projectOverview: "项目概述",
    error: "错误",
    errorFetchingData: "获取数据时出错。请稍后再试。",
    matrixAiAgent: "矩阵人工智能代理",
    home: "首页",
    agentDescription: "与我们的高级AI代理互动，该代理经过Matrix原则训练。通过自然对话解锁数字领域的秘密。",
    capabilities: "功能",
    nlpCapability: "自然语言处理",
    marketAnalysis: "市场分析和代币发布",
    problemSolving: "高级问题解决",
    accessAgent: "访问AI代理",
    aiAgentInterface: "矩阵AI代理界面",
    aiLaunchedTokens: "AI发布的代币",
    launchDate: "发布日期",
    matrixAiDesc: "分析市场条件后推出的AI驱动DeFi协议",
    neuralNetDesc: "去中心化机器学习网络代币",
    cyberCoreDesc: "去中心化系统的AI治理代币"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage,
      translations: translations[language]
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
